name: Publish

on:
  push:
    tags:
      - '**.**'
      - '**.**.*'

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build --no-cache . --tag ghcr.io/eriksoderblom/alpine-apache-php:latest --tag ghcr.io/eriksoderblom/alpine-apache-php:$(git describe --tags --abbrev=0)
        docker push ghcr.io/eriksoderblom/alpine-apache-php:latest
        docker push ghcr.io/eriksoderblom/alpine-apache-php:$(git describe --tags --abbrev=0)